"""add_collections

Revision ID: 99c0ab3a26cf
Revises: c3b8d2a4e571
Create Date: 2026-05-23 11:41:31.457781

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "99c0ab3a26cf"
down_revision: Union[str, Sequence[str], None] = "c3b8d2a4e571"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collection",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("poster_path", sa.String(), nullable=True),
        sa.Column("backdrop_path", sa.String(), nullable=True),
        sa.Column("overview", sa.Text(), nullable=True),
        sa.Column("details_refreshed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("index_refreshed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_collection_name"), "collection", ["name"], unique=False)
    op.create_table(
        "collection_movie",
        sa.Column("collection_id", sa.Integer(), nullable=False),
        sa.Column("movie_id", sa.Integer(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id"], ["collection.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("collection_id", "movie_id"),
    )
    op.create_table(
        "user_collection_ranking",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("collection_id", sa.Integer(), nullable=False),
        sa.Column("movie_id", sa.Integer(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["collection_id"], ["collection.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "collection_id", "movie_id", name="uq_user_collection_movie"
        ),
    )
    op.create_index(
        op.f("ix_user_collection_ranking_collection_id"),
        "user_collection_ranking",
        ["collection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_collection_ranking_user_id"),
        "user_collection_ranking",
        ["user_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_for_you_cache_user_id"), table_name="for_you_cache")
    op.drop_table("for_you_cache")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_collection_ranking_user_id"),
        table_name="user_collection_ranking",
    )
    op.drop_index(
        op.f("ix_user_collection_ranking_collection_id"),
        table_name="user_collection_ranking",
    )
    op.drop_table("user_collection_ranking")
    op.drop_table("collection_movie")
    op.drop_index(op.f("ix_collection_name"), table_name="collection")
    op.drop_table("collection")
    # ### end Alembic commands ###
